Repository DockyardMC/Dockyard, pull requests merged in 2024-10, with the labels that each got.

#66 Fix interaction events being fired twice
  src/main/kotlin/io/github/dockyardmc/Main.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundEntityInteractPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundUseItemOnPacket.kt
  src/main/kotlin/io/github/dockyardmc/utils/InteractionTimeout.kt
  src/main/kotlin/io/github/dockyardmc/utils/Utils.kt
Labels: size/S, priority:1, area/packets, area/entities, area/world, type/code-quality, type/reliability, hacktoberfest, hacktoberfest-accepted

#59 Feature/Item Builder
  src/main/kotlin/io/github/dockyardmc/item/ItemBuilder.kt
  src/main/kotlin/io/github/dockyardmc/item/ItemComponentWriter.kt
  src/main/kotlin/io/github/dockyardmc/location/Location.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
Labels: size/S, priority:3, area/inventory, area/utils, type/code-quality

#74 Added withProfile for setting player head data.
  src/main/kotlin/io/github/dockyardmc/item/ItemBuilder.kt
Labels: size/S, priority:3, area/packets, area/inventory, area/utils, type/code-quality

#76 Feature/bounds
  src/main/kotlin/io/github/dockyardmc/Main.kt
  src/main/kotlin/io/github/dockyardmc/blocks/BatchBlockUpdate.kt
  src/main/kotlin/io/github/dockyardmc/bounds/Bound.kt
  src/main/kotlin/io/github/dockyardmc/events/PlayerEnterBoundEvent.kt
  src/main/kotlin/io/github/dockyardmc/events/PlayerLeaveBoundEvent.kt
  src/main/kotlin/io/github/dockyardmc/location/Location.kt
  src/main/kotlin/io/github/dockyardmc/runnables/AsyncQueueProcessor.kt
  src/main/kotlin/io/github/dockyardmc/runnables/AsyncRunnable.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
Labels: size/M, priority:1, area/world, area/utils, type/reliability, type/missing-implementation, hacktoberfest

#77 fix: reset styling after server brand
  src/main/kotlin/io/github/dockyardmc/protocol/packets/configurations/ConfigurationHandler.kt
Labels: hacktoberfest, hacktoberfest-accepted
