Repository DockyardMC/Dockyard, pull requests merged in 2025-03, with the labels that each got.

#104 fix clipping through ceiling when flying
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPlayerCommandPacket.kt
Labels: size/S, priority:3, area/packets, area/entities, type/code-quality, type/reliability

#106 fix(events): dispatch InventoryItemChangeEvent
  src/main/kotlin/io/github/dockyardmc/inventory/EntityInventory.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
Labels: size/S, priority:2, area/events, area/inventory, type/reliability

#112 Fix being able to login with multiple accounts at the same time
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/player/PlayerManager.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/login/LoginHandler.kt
Labels: size/M

#115 Feature/metadata fixes
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/entity/TestZombie.kt
  src/main/kotlin/io/github/dockyardmc/entity/handlers/EntityMetadataHandler.kt
  src/main/kotlin/io/github/dockyardmc/events/CancellableEvent.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedByteBuf.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedMutableList.kt
  src/main/kotlin/io/github/dockyardmc/inventory/PlayerInventory.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundStopSoundPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundEntityInteractPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/registry/ClientPacketRegistry.kt
Labels: size/L

#116 Rewrite some commands to match vanilla and add /list
  build.gradle.kts
  src/main/kotlin/io/github/dockyardmc/DockyardServer.kt
  src/main/kotlin/io/github/dockyardmc/commands/ArgumentTypes.kt
  src/main/kotlin/io/github/dockyardmc/commands/CommandHandler.kt
  src/main/kotlin/io/github/dockyardmc/config/Config.kt
  src/main/kotlin/io/github/dockyardmc/implementations/DefaultImplementationModule.kt
  src/main/kotlin/io/github/dockyardmc/implementations/block/DefaultBlockHandlers.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/ClearCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/DebugCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/DefaultCommands.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/GamemodeCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/ListCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/SchedulerCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/SoundCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/TimeCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/VersionAndHelpCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/WorldCommand.kt
  src/main/kotlin/io/github/dockyardmc/motd/ServerStatus.kt
  src/main/kotlin/io/github/dockyardmc/utils/DockyardBranding.kt
Labels: size/L

#119 Fix/random things
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/player/systems/EntityViewSystem.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPlayerCommandPacket.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
Labels: size/M, priority:1, area/packets, area/entities, type/code-quality, type/reliability

#120 Add attributes
  .idea/jarRepositories.xml
  .idea/modules.xml
  build.gradle.kts
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/DockyardServer.kt
  src/main/kotlin/io/github/dockyardmc/attributes/Attribute.kt
  src/main/kotlin/io/github/dockyardmc/attributes/AttributeInstance.kt
  src/main/kotlin/io/github/dockyardmc/attributes/PlayerAttributes.kt
  src/main/kotlin/io/github/dockyardmc/effects/PotionEffectAttributes.kt
  src/main/kotlin/io/github/dockyardmc/effects/PotionEffectImpl.kt
  src/main/kotlin/io/github/dockyardmc/entity/handlers/EntityPotionEffectsHandler.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/profiler/Profiler.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundUpdateAttributesPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/registry/ClientPacketRegistry.kt
  src/main/kotlin/io/github/dockyardmc/registry/Attributes.kt
  src/main/kotlin/io/github/dockyardmc/registry/RegistryManager.kt
  src/main/kotlin/io/github/dockyardmc/registry/registries/AttributeRegistry.kt
  src/main/kotlin/io/github/dockyardmc/world/WorldManager.kt
  src/main/resources/registry/attribute_registry.json.gz
  src/test/kotlin/io/github/dockyard/tests/RegistryTests.kt
  src/test/kotlin/io/github/dockyard/tests/scheduler/SchedulerTest.kt
Labels: size/XL

#121 Add bunch of optimizations to navigator
  build.gradle.kts
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/events/EntityNavigatorPickOffsetEvent.kt
  src/main/kotlin/io/github/dockyardmc/pathfinding/Navigator.kt
Labels: size/M

#122 add interaction entity
  gradle.properties
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/entity/EntityMetadata.kt
  src/main/kotlin/io/github/dockyardmc/entity/InteractionEntity.kt
Labels: size/L

#123 Add eye height location
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
Labels: size/XS

#124 Add `itemDropEntity` field to the `EntityPickupItemEvent` event
  src/main/kotlin/io/github/dockyardmc/entity/handlers/EntityItemPickupHandler.kt
  src/main/kotlin/io/github/dockyardmc/events/EntityPickupItemEvent.kt
Labels: size/XS

#127 Make AIManager disposable
  src/main/kotlin/io/github/dockyardmc/entity/ai/AIManager.kt
Labels: size/S
