Repository DockyardMC/Dockyard, pull requests merged in 2025-05, with the labels that each got.

#155 add raw field to kick method
  src/main/kotlin/io/github/dockyardmc/protocol/PlayerNetworkManager.kt
Labels: size/XS

#156 Add various block handlers to match vanilla building
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/implementations/block/DefaultBlockHandlers.kt
  src/main/kotlin/io/github/dockyardmc/item/ItemStackMeta.kt
  src/main/kotlin/io/github/dockyardmc/location/Location.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/player/ProtocolEnums.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundUseItemOnBlockPacket.kt
  src/main/kotlin/io/github/dockyardmc/world/block/Block.kt
  src/main/kotlin/io/github/dockyardmc/world/block/DebugStick.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/BlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/BlockHandlerUtil.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/DoorBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/DoublePlantBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/FenceBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/SlabBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/SnowLayerBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/StairBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/Chunk.kt
Labels: size/XL

#158 Refactor the Sidebar API
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/apis/sidebar/Sidebar.kt
  src/main/kotlin/io/github/dockyardmc/apis/sidebar/SidebarLines.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedCustomColor.kt
  src/main/kotlin/io/github/dockyardmc/utils/DebugSidebar.kt
  src/main/kotlin/io/github/dockyardmc/utils/RangeColorMapper.kt
Labels: size/L, priority:3, area/utils, area/other, type/code-quality, type/cosmetic, area/ui

#159 Fix ping packets
  src/main/kotlin/io/github/dockyardmc/protocol/packets/handshake/ServerboundPingRequestPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundPlayPingResponsePacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPlayPingRequestPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/registry/ServerPacketRegistry.kt
Labels: size/M

#162 Update readme
  README.md
Labels: size/M, type/documentation

#164 Add Heightmaps and Weather
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/entity/LightningBolt.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedMutableList.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedNBTCombound.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/DefaultCommands.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/WeatherCommand.kt
  src/main/kotlin/io/github/dockyardmc/maths/MathUtils.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/AnimationProvider.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundChunkDataPacket.kt
  src/main/kotlin/io/github/dockyardmc/utils/bitstorage/BitStorage.kt
  src/main/kotlin/io/github/dockyardmc/utils/bitstorage/SimpleBitStorage.kt
  src/main/kotlin/io/github/dockyardmc/world/Weather.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
  src/main/kotlin/io/github/dockyardmc/world/WorldManager.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/Chunk.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/ChunkHeightmap.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/ChunkPos.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/ChunkSection.kt
Labels: size/XL

#165 Added *some* block handlers
  src/main/kotlin/io/github/dockyardmc/implementations/block/DefaultBlockHandlers.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundUseItemOnBlockPacket.kt
  src/main/kotlin/io/github/dockyardmc/utils/InteractionTimeout.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/AxisFacingBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/BlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/BlockHandlerUtil.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/CandleBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/ChiseledBookshelfBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/DirtBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/DirtPathBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/DoorBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/FacingBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/FenceBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/GrassBlockBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/LogBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/ShulkerboxBlockHandler.kt
  src/main/kotlin/io/github/dockyardmc/world/block/handlers/TrapdoorBlockHandler.kt
Labels: size/L, area/world, type/code-quality, type/cosmetic, type/missing-implementation

#171 add lock to `ChunkViewSystem` to prevent chunk updates from both worlds when transitioning
  .idea/modules.xml
  src/main/kotlin/io/github/dockyardmc/world/PlayerChunkViewSystem.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
Labels: size/S

#180 fix `world.join` not ensuring player gets properly teleported to intended location
  src/main/kotlin/io/github/dockyardmc/DockyardServer.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
Labels: size/S

#181 Fix `player.sendSystemMessage` raising `ServerSendPlayerMessageEvent`
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/test/kotlin/io/github/dockyard/tests/events/ServerSendPlayerMessageEventTest.kt
Labels: size/S
