Repository DockyardMC/Dockyard, pull requests merged in 2025-04, with the labels that each got.

#138 Add a bandwidth counter server metric
  build.gradle.kts
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/apis/sidebar/Sidebar.kt
  src/main/kotlin/io/github/dockyardmc/entity/InteractionEntity.kt
  src/main/kotlin/io/github/dockyardmc/entity/ai/goals/RandomWalkAroundGoal.kt
  src/main/kotlin/io/github/dockyardmc/events/system/EventSystem.kt
  src/main/kotlin/io/github/dockyardmc/maths/MathUtils.kt
  src/main/kotlin/io/github/dockyardmc/protocol/decoders/PacketLengthDecoder.kt
  src/main/kotlin/io/github/dockyardmc/protocol/encoders/PacketLengthEncoder.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundChunkDataPacket.kt
  src/main/kotlin/io/github/dockyardmc/schematics/Schematic.kt
  src/main/kotlin/io/github/dockyardmc/server/ServerMetrics.kt
  src/main/kotlin/io/github/dockyardmc/utils/DataSizeCounter.kt
  src/main/kotlin/io/github/dockyardmc/utils/DebugSidebar.kt
  src/main/kotlin/io/github/dockyardmc/world/BiomeBuilder.kt
  src/main/kotlin/io/github/dockyardmc/world/PlayerChunkViewSystem.kt
  src/main/kotlin/io/github/dockyardmc/world/World.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/Chunk.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/ChunkPos.kt
  src/main/kotlin/io/github/dockyardmc/world/chunk/ChunkUtils.kt
  src/test/kotlin/io/github/dockyard/tests/block/BlockTest.kt
  src/test/kotlin/io/github/dockyard/tests/utils/DataSizeCounterTest.kt
Labels: size/L

#139 Add way to set player velocity
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/location/Location.kt
  src/main/kotlin/io/github/dockyardmc/maths/vectors/Vector3d.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundSetEntityVelocityPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundSpawnEntityPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundClientInputPacket.kt
  src/main/kotlin/io/github/dockyardmc/utils/Velocity.kt
Labels: size/L, priority:1, area/packets, area/entities, type/missing-implementation

#142 fix bossbar being visible after disposing
  src/main/kotlin/io/github/dockyardmc/apis/bossbar/Bossbar.kt
Labels: size/XS

#146 Fix bossbar not removing viewers when they leave
  src/main/kotlin/io/github/dockyardmc/apis/bossbar/Bossbar.kt
Labels: size/XS

#147 Change potion effect time from ticks to kotlin duration
  src/main/kotlin/io/github/dockyardmc/commands/ArgumentTypes.kt
  src/main/kotlin/io/github/dockyardmc/commands/CommandHandler.kt
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/entity/handlers/EntityPotionEffectsHandler.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/DefaultCommands.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/EffectCommand.kt
  src/main/kotlin/io/github/dockyardmc/registry/PotionEffects.kt
  src/main/kotlin/io/github/dockyardmc/scheduler/runnables/AsyncTimedSequence.kt
  src/main/kotlin/io/github/dockyardmc/utils/UpdateChecker.kt
  src/test/kotlin/io/github/dockyard/tests/command/CommandTest.kt
  src/test/kotlin/io/github/dockyard/tests/command/GeneralCommandFrameworkTest.kt
  src/test/kotlin/io/github/dockyard/tests/entity/EffectsTest.kt
Labels: priority:3, area/entities, area/commands, area/utils, type/code-quality, size/XL

#148 add way to get nearest highest, lowest points
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/location/Location.kt
  src/test/kotlin/io/github/dockyard/tests/location/HighestLowestPointTest.kt
Labels: size/L, priority:3, area/world, area/utils, type/code-quality

#149 Add `RollingCounter` util class
  .idea/inspectionProfiles/Project_Default.xml
  .idea/structuralSearch.xml
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/maths/MathUtils.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/AnimationProvider.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounter.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterDouble.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterFloat.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterInt.kt
  src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterLong.kt
  src/main/kotlin/io/github/dockyardmc/registry/registries/BlockRegistry.kt
  src/main/kotlin/io/github/dockyardmc/scheduler/AsyncSchedulerTask.kt
  src/main/kotlin/io/github/dockyardmc/scheduler/GlobalScheduler.kt
  src/main/kotlin/io/github/dockyardmc/scheduler/Scheduler.kt
  src/main/kotlin/io/github/dockyardmc/world/palette/AdaptivePalette.kt
  src/main/kotlin/io/github/dockyardmc/world/palette/PaletteWriter.kt
Labels: size/L, priority:3, area/utils, type/cosmetic, area/ui

#150 Add permission system
  .idea/inspectionProfiles/Project_Default.xml
  src/main/kotlin/Main.kt
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedMutableList.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/player/permissions/PermissionGroup.kt
  src/main/kotlin/io/github/dockyardmc/player/permissions/PermissionHolder.kt
  src/main/kotlin/io/github/dockyardmc/player/permissions/PermissionManager.kt
  src/main/kotlin/io/github/dockyardmc/player/permissions/PermissionSystem.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundEntityEventPacket.kt
  src/test/kotlin/io/github/dockyard/tests/permissions/PermissionGroupTest.kt
  src/test/kotlin/io/github/dockyard/tests/permissions/PlayerPermissionTest.kt
Labels: size/L

#137 Add Advancements API
  gradlew
  src/main/kotlin/io/github/dockyardmc/advancement/Advancement.kt
  src/main/kotlin/io/github/dockyardmc/advancement/AdvancementBuilder.kt
  src/main/kotlin/io/github/dockyardmc/advancement/AdvancementFrame.kt
  src/main/kotlin/io/github/dockyardmc/advancement/PlayerAdvancementTracker.kt
  src/main/kotlin/io/github/dockyardmc/apis/advancement/Toast.kt
  src/main/kotlin/io/github/dockyardmc/events/PlayerSelectAdvancementsTabEvent.kt
  src/main/kotlin/io/github/dockyardmc/extentions/ExtendedByteBuf.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
  src/main/kotlin/io/github/dockyardmc/protocol/Optional.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundSelectAdvancementsTabPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundUpdateAdvancementsPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundSelectAdvancementsTabPacket.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/registry/ClientPacketRegistry.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/registry/ServerPacketRegistry.kt
  src/test/kotlin/io/github/dockyard/tests/advancements/AdvancementTest.kt
  src/test/kotlin/io/github/dockyard/tests/events/PlayerSelectAdvancementsTabEventTest.kt
Labels: priority:2, area/packets, area/other, type/cosmetic, type/missing-implementation, size/XL

#151 update some system messages
  src/main/kotlin/io/github/dockyardmc/implementations/commands/ListCommand.kt
  src/main/kotlin/io/github/dockyardmc/implementations/commands/VersionAndHelpCommand.kt
  src/main/kotlin/io/github/dockyardmc/motd/ServerStatus.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/configurations/ConfigurationHandler.kt
  src/main/kotlin/io/github/dockyardmc/protocol/packets/login/LoginHandler.kt
  src/main/kotlin/io/github/dockyardmc/registry/registries/MinecraftVersionRegistry.kt
  src/main/kotlin/io/github/dockyardmc/utils/Resources.kt
Labels: size/M

#153 fix: reset style after server brand
  src/main/kotlin/io/github/dockyardmc/protocol/packets/configurations/ConfigurationHandler.kt
Labels: size/XS

#152 Change a couple of bindables from var to val
  src/main/kotlin/io/github/dockyardmc/apis/Hologram.kt
  src/main/kotlin/io/github/dockyardmc/entity/DisplayEntity.kt
  src/main/kotlin/io/github/dockyardmc/entity/ElderGuardian.kt
  src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
  src/main/kotlin/io/github/dockyardmc/entity/Guardian.kt
  src/main/kotlin/io/github/dockyardmc/entity/InteractionEntity.kt
  src/main/kotlin/io/github/dockyardmc/entity/ItemDropEntity.kt
  src/main/kotlin/io/github/dockyardmc/entity/Parrot.kt
  src/main/kotlin/io/github/dockyardmc/entity/Ravager.kt
  src/main/kotlin/io/github/dockyardmc/entity/Squid.kt
  src/main/kotlin/io/github/dockyardmc/entity/TestZombie.kt
  src/main/kotlin/io/github/dockyardmc/entity/Warden.kt
  src/main/kotlin/io/github/dockyardmc/inventory/PlayerInventory.kt
  src/main/kotlin/io/github/dockyardmc/npc/PlayerNpc.kt
  src/main/kotlin/io/github/dockyardmc/player/Player.kt
Labels: size/M
